# Generated by Django 4.2.23 on 2025-09-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpusapp', '0010_entry_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
                ('count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-count'],
            },
        ),
    ]
